USE [GD1C2024]
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'QUICK_SORT')
    EXEC('CREATE SCHEMA QUICK_SORT')
GO

IF NOT EXISTS(SELECT name FROM sys.procedures WHERE name = 'DROP_TABLES')
    EXEC('CREATE PROCEDURE [QUICK_SORT].[DROP_TABLES] AS BEGIN SET NOCOUNT ON; END');
GO

ALTER PROCEDURE [QUICK_SORT].[DROP_TABLES]
AS
BEGIN
    DECLARE @sql NVARCHAR(500) = ''
    
    DECLARE cursorTablas CURSOR FOR
    SELECT DISTINCT 'ALTER TABLE [' + tc.TABLE_SCHEMA + '].[' +  tc.TABLE_NAME + '] DROP [' + rc.CONSTRAINT_NAME + '];'
    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    ON tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
    WHERE tc.TABLE_SCHEMA = 'QUICK_SORT'

    OPEN cursorTablas
    FETCH NEXT FROM cursorTablas INTO @sql

    WHILE (@@FETCH_STATUS = 0)
    BEGIN
        EXEC sp_executesql @sql
        FETCH NEXT FROM cursorTablas INTO @Sql
    END

    CLOSE cursorTablas
    DEALLOCATE cursorTablas
    
    EXEC sp_MSforeachtable 'DROP TABLE ?', @whereand='AND schema_name(schema_id) = ''QUICK_SORT'' AND o.name NOT LIKE ''BI_%'''
END
GO

EXEC [QUICK_SORT].[DROP_TABLES]
GO

IF NOT EXISTS(SELECT name FROM sys.procedures WHERE name='CREATE_TABLES')
   EXEC('CREATE PROCEDURE [QUICK_SORT].[CREATE_TABLES] AS BEGIN SET NOCOUNT ON; END');
GO

ALTER PROCEDURE [QUICK_SORT].[CREATE_TABLES]
AS
BEGIN

		CREATE TABLE [QUICK_SORT].PRODUCTO_CATEGORIA(
			PRODUCTO_CATEGORIA_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			PRODUCTO_CATEGORIA NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].PRODUCTO_SUB_CATEGORIA(
			PRODUCTO_SUB_CATEGORIA_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			PRODUCTO_CATEGORIA_ID INTEGER REFERENCES[QUICK_SORT].[PRODUCTO_CATEGORIA] NOT NULL,
			PRODUCTO_SUB_CATEGORIA NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[PRODUCTO](
			PRODUCTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			PRODUCTO_SUB_CATEGORIA_ID INTEGER REFERENCES[QUICK_SORT].[PRODUCTO_SUB_CATEGORIA] NOT NULL,
			PRODUCTO_NOMBRE NVARCHAR(255),
			PRODUCTO_DESCRIPCION NVARCHAR(255),
			PRODUCTO_PRECIO DECIMAL(18,2),
			PRODUCTO_MARCA NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[PROVINCIA](
			PROVINCIA_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			PROVINCIA NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[LOCALIDAD](
			LOCALIDAD_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			PROVINCIA_ID INTEGER REFERENCES [QUICK_SORT].[PROVINCIA] NOT NULL,
			LOCALIDAD NVARCHAR(255)
		);
		
		CREATE TABLE [QUICK_SORT].[DIRECCION](
			DIRECCION_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			LOCALIDAD_ID INTEGER REFERENCES [QUICK_SORT].[LOCALIDAD] NOT NULL,
			DIRECCION NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[MEDIO_PAGO_TIPO] (
			MEDIO_PAGO_TIPO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			MEDIO_PAGO_TIPO NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[PAGO_MEDIO_PAGO] (
			PAGO_MEDIO_PAGO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			MEDIO_PAGO_TIPO_ID INTEGER NOT NULL,
			PAGO_MEDIO_PAGO NVARCHAR(255) NOT NULL,
			FOREIGN KEY (MEDIO_PAGO_TIPO_ID) REFERENCES [QUICK_SORT].[MEDIO_PAGO_TIPO](MEDIO_PAGO_TIPO_ID)
		);

		CREATE TABLE [QUICK_SORT].[DESCUENTO_MEDIO_PAGO](
			DESCUENTO_MEDIO_PAGO_CODIGO DECIMAL(18,0) PRIMARY KEY,
			DESCUENTO_PAGO_MEDIO_PAGO_ID INTEGER REFERENCES [QUICK_SORT].[PAGO_MEDIO_PAGO] NOT NULL,
			DESCUENTO_FECHA_INICIO DATETIME,
			DESCUENTO_FECHA_FIN DATETIME,
			DESCUENTO_PORCENTAJE DECIMAL(18,2),
			DESCUENTO_TOPE DECIMAL(18,2),
			DESCUENTO_DESCRIPCION NVARCHAR(255)
		); 

		CREATE TABLE [QUICK_SORT].[SUPERMERCADO](
			SUPER_CUIT NVARCHAR(255) PRIMARY KEY,
			SUPER_DIRECCION_ID INTEGER REFERENCES [QUICK_SORT].[DIRECCION] NOT NULL,
			SUPER_NOMBRE NVARCHAR(255),
			SUPER_RAZON_SOC NVARCHAR(255),
			SUPER_IIBB NVARCHAR(255),
			SUPER_FECHA_INI_ACTIVIDAD DATETIME,
			SUPER_CONDICION_FISCAL NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[SUCURSAL](
			SUCURSAL_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			SUCURSAL_SUPER_CUIT NVARCHAR(255) REFERENCES [QUICK_SORT].[SUPERMERCADO] NOT NULL,
			SUCURSAL_DIRECCION_ID INTEGER REFERENCES [QUICK_SORT].[DIRECCION] NOT NULL,
			SUCURSAL_NOMBRE NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[EMPLEADO](
			EMPLEADO_LEGAJO INTEGER IDENTITY(1,1) PRIMARY KEY,
			EMPLEADO_SUCURSAL_ID INTEGER REFERENCES [QUICK_SORT].[SUCURSAL] NOT NULL,
			EMPLEADO_NOMBRE NVARCHAR(255),
			EMPLEADO_APELLIDO NVARCHAR(255),
			EMPLEADO_FECHA_REGISTRO DATETIME,
			EMPLEADO_TELEFONO DECIMAL(18,0),
			EMPLEADO_MAIL NVARCHAR(255),
			EMPLEADO_FECHA_NACIMIENTO DATE,
			EMPLEADO_DNI DECIMAL(18,0)
		);

		CREATE TABLE [QUICK_SORT].[CLIENTE] (
			CLIENTE_ID INTEGER IDENTITY (1,1) PRIMARY KEY, --para los id que no estan en la maestra
			CLIENTE_DIRECCION_ID INTEGER NOT NULL,
			CLIENTE_DNI DECIMAL(18,0) NOT NULL,
			CLIENTE_NOMBRE NVARCHAR(255) NOT NULL,
			CLIENTE_APELLIDO NVARCHAR(255) NOT NULL,
			CLIENTE_FECHA_REGISTRO DATETIME NOT NULL,
			CLIENTE_TELEFONO DECIMAL(18,0),
			CLIENTE_MAIL NVARCHAR(255),
			CLIENTE_FECHA_NACIMIENTO DATE,
			FOREIGN KEY (CLIENTE_DIRECCION_ID) REFERENCES [QUICK_SORT].[DIRECCION](DIRECCION_ID)
		);

		CREATE TABLE [QUICK_SORT].[TICKET_TIPO_COMPROBANTE](
			TICKET_TIPO_COMPROBANTE_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			TICKET_TIPO_COMPROBANTE NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[CAJA_TIPO](
			CAJA_TIPO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			CAJA_TIPO NVARCHAR(255)
		);
		CREATE TABLE [QUICK_SORT].[ESTADO](
			ESTADO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			ESTADO_TIPO NVARCHAR(255)
		);

		CREATE TABLE [QUICK_SORT].[CAJA](
			CAJA_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			CAJA_SUCURSAL_ID INTEGER REFERENCES [QUICK_SORT].[SUCURSAL] NOT NULL,
			CAJA_TIPO_ID INTEGER REFERENCES [QUICK_SORT].[CAJA_TIPO] NOT NULL,
			CAJA_NUMERO DECIMAL(18,0)
		);

		CREATE TABLE [QUICK_SORT].[TICKET](
			TICKET_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			TICKET_SUCURSAL_ID INTEGER REFERENCES [QUICK_SORT].[SUCURSAL] NOT NULL,
			TICKET_EMPLEADO_LEGAJO INTEGER REFERENCES [QUICK_SORT].[EMPLEADO] NOT NULL,
			TICKET_CAJA_ID INTEGER REFERENCES [QUICK_SORT].[CAJA] NOT NULL,
			TICKET_TIPO_COMPROBANTE_ID INTEGER REFERENCES [QUICK_SORT].[TICKET_TIPO_COMPROBANTE] NOT NULL,
			TICKET_NRO DECIMAL(18,0),
			TICKET_TOTAL DECIMAL(18,2),
			TICKET_FECHA_HORA DATETIME,
			TICKET_SUBTOTAL_PRODUCTOS DECIMAL(18,2),
			TICKET_DESCUENTO_MEDIO DECIMAL(18,2),
			TICKET_TOTAL_PROMOCIONES DECIMAL(18,2),
			TICKET_TOTAL_ENVIO DECIMAL(18,2)
		);

		CREATE TABLE [QUICK_SORT].[ENVIO] (
			ENVIO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			ENVIO_TICKET_ID INTEGER NOT NULL,
			ENVIO_CLIENTE_ID INTEGER NOT NULL,
			ENVIO_FECHA_PROGRAMADA DATETIME,
			ENVIO_HORA_INICIO DECIMAL(18,0),
			ENVIO_HORA_FIN DECIMAL(18,0),
			ENVIO_FECHA_ENTREGA DATETIME,
			ENVIO_COSTO DECIMAL(18,2),
			FOREIGN KEY (ENVIO_TICKET_ID) REFERENCES [QUICK_SORT].[TICKET](TICKET_ID),
			FOREIGN KEY (ENVIO_CLIENTE_ID) REFERENCES [QUICK_SORT].[CLIENTE](CLIENTE_ID)
		);

		-- TODO: Se le elimino estado_fecha_inicio por seguimiento del DER
		CREATE TABLE [QUICK_SORT].[ESTADO_POR_ENVIO](
			ESTADO_ID INTEGER REFERENCES [QUICK_SORT].[ESTADO] NOT NULL,
			ENVIO_ID INTEGER REFERENCES [QUICK_SORT].[ENVIO] NOT NULL,
			PRIMARY KEY(ESTADO_ID, ENVIO_ID)
		);

		CREATE TABLE [QUICK_SORT].[DETALLE_TICKET](
			DETALLE_TICKET_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			DETALLE_TICKET_TICKET_ID INTEGER REFERENCES [QUICK_SORT].[TICKET] NOT NULL,
			PRODUCTO_ID INTEGER REFERENCES [QUICK_SORT].[PRODUCTO] NOT NULL,
			DETALLE_CANTIDAD DECIMAL(18,0),
			DETALLE_PRECIO_UNITARIO DECIMAL(18,2),
			DETALLE_TOTAL_PRODUCTO DECIMAL(18,2)
			);		

		CREATE TABLE [QUICK_SORT].PROMOCION(
			PROMO_CODIGO DECIMAL(18,0)  PRIMARY KEY,
        	PROMO_DESCRIPCION NVARCHAR(255),
        	PROMO_FECHA_INICIO DATETIME,
        	PROMO_FECHA_FIN DATETIME
		);

		CREATE TABLE [QUICK_SORT].REGLA_PROMOCION_PRODUCTO(
			PROMO_CODIGO DECIMAL(18,0) REFERENCES [QUICK_SORT].[PROMOCION],
        	PRODUCTO_ID INTEGER REFERENCES [QUICK_SORT].[PRODUCTO],
        	PRIMARY KEY (PROMO_CODIGO, PRODUCTO_ID)
		);

		CREATE TABLE [QUICK_SORT].REGLA_PROMOCION(
			REGLA_PROMOCION_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			REGLA_PROMO_CODIGO DECIMAL(18,0) REFERENCES [QUICK_SORT].[PROMOCION],
			REGLA_DESCRIPCION NVARCHAR(255),
			REGLA_DESCUENTO_APLICABLE DECIMAL(18,2),
			REGLA_CANTIDAD_APLICABLE DECIMAL(18,0),
			REGLA_CANTIDAD_APLICABLE_DESCUENTO DECIMAL(18,0),
			REGLA_CANTIDAD_MAXIMA DECIMAL(18,0),
			REGLA_APLICA_MISMA_MARCA DECIMAL (18,0),
			REGLA_APLICA_MISMO_PRODUCTO DECIMAL (18,0)
		);

		CREATE TABLE [QUICK_SORT].DETALLE_POR_PROMOCION(
			DETALLE_TICKET_ID INTEGER REFERENCES [QUICK_SORT].[DETALLE_TICKET] NOT NULL,
			PROMO_CODIGO DECIMAL(18,0) REFERENCES [QUICK_SORT].[PROMOCION] NOT NULL,
			PROMO_TOTAL DECIMAL(18,2),
			PRIMARY KEY (DETALLE_TICKET_ID,PROMO_CODIGO)
		);

		CREATE TABLE [QUICK_SORT].[DETALLE_PAGO] (
			DETALLE_PAGO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			DET_PAGO_CLIENTE_ID INTEGER REFERENCES [QUICK_SORT].[CLIENTE],
			DET_PAGO_NRO_TARJETA NVARCHAR(50) NOT NULL,
			DET_PAGO_FECHA_VEN_TARJETA DATETIME NOT NULL,
			DET_PAGO_CUOTAS DECIMAL(18,0) NOT NULL,
		);
     
		CREATE TABLE [QUICK_SORT].[PAGO] (
			PAGO_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
			PAGO_TICKET_ID INTEGER NOT NULL,
			PAGO_MEDIO_PAGO_ID INTEGER NOT NULL,
			DETALLE_PAGO_ID INTEGER NOT NULL,
			PAGO_FECHA DATETIME NOT NULL,
			PAGO_IMPORTE DECIMAL(18,2) NOT NULL,
			PAGO_DESCUENTO_APLICADO DECIMAL(18,2),
			FOREIGN KEY (PAGO_TICKET_ID) REFERENCES [QUICK_SORT].[TICKET](TICKET_ID),
			FOREIGN KEY (PAGO_MEDIO_PAGO_ID) REFERENCES [QUICK_SORT].[PAGO_MEDIO_PAGO](PAGO_MEDIO_PAGO_ID),
			FOREIGN KEY (DETALLE_PAGO_ID) REFERENCES [QUICK_SORT].[DETALLE_PAGO](DETALLE_PAGO_ID)
		);
	 
END
GO
-- Ejecutar procedimiento para crear tablas
EXEC [QUICK_SORT].[CREATE_TABLES]
GO

ALTER PROCEDURE [QUICK_SORT].[MIGRAR]
AS
BEGIN

	-- PRODUCTO_CATEGORIA

	INSERT INTO [QUICK_SORT].[PRODUCTO_CATEGORIA] (PRODUCTO_CATEGORIA)
		SELECT DISTINCT PRODUCTO_CATEGORIA
		FROM [gd_esquema].[Maestra]
		WHERE PRODUCTO_CATEGORIA IS NOT NULL

	-- PRODUCTO_SUB_CATEGORIA

	INSERT INTO [QUICK_SORT].[PRODUCTO_SUB_CATEGORIA] (PRODUCTO_CATEGORIA_ID,PRODUCTO_SUB_CATEGORIA)
		SELECT DISTINCT p.PRODUCTO_CATEGORIA_ID,m.PRODUCTO_SUB_CATEGORIA
		FROM [gd_esquema].[Maestra] m JOIN [QUICK_SORT].[PRODUCTO_CATEGORIA] p ON  p.PRODUCTO_CATEGORIA = m.PRODUCTO_CATEGORIA
		WHERE PRODUCTO_SUB_CATEGORIA IS NOT NULL
	
	-- PRODUCTO

	INSERT INTO [QUICK_SORT].[PRODUCTO]( PRODUCTO_SUB_CATEGORIA_ID, PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, PRODUCTO_MARCA)
		SELECT DISTINCT p.PRODUCTO_SUB_CATEGORIA_ID,PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, PRODUCTO_MARCA 
		FROM [gd_esquema].[Maestra] m JOIN [QUICK_SORT].[PRODUCTO_SUB_CATEGORIA] p ON p.PRODUCTO_SUB_CATEGORIA = m.PRODUCTO_SUB_CATEGORIA
		WHERE PRODUCTO_NOMBRE IS NOT NULL
		AND PRODUCTO_DESCRIPCION IS NOT NULL
		AND PRODUCTO_PRECIO IS NOT NULL
		AND PRODUCTO_MARCA IS NOT NULL

	-- PROVINCIA

    INSERT INTO [QUICK_SORT].[PROVINCIA] (PROVINCIA)
        SELECT DISTINCT SUCURSAL_PROVINCIA
        FROM [gd_esquema].[Maestra]
        WHERE SUCURSAL_PROVINCIA IS NOT NULL
        UNION
        SELECT DISTINCT SUPER_PROVINCIA
        FROM [gd_esquema].[Maestra]
        WHERE SUPER_PROVINCIA IS NOT NULL
		UNION
		SELECT DISTINCT CLIENTE_PROVINCIA
		FROM [gd_esquema].Maestra
		WHERE CLIENTE_PROVINCIA IS NOT NULL
	
	-- LOCALIDAD

	INSERT INTO [QUICK_SORT].[LOCALIDAD] (PROVINCIA_ID, LOCALIDAD)
		SELECT DISTINCT PROVINCIA_ID, SUPER_LOCALIDAD
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].PROVINCIA ON SUPER_PROVINCIA = PROVINCIA
		WHERE SUPER_LOCALIDAD IS NOT NULL
		UNION
		SELECT DISTINCT PROVINCIA_ID, SUCURSAL_LOCALIDAD
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].PROVINCIA ON SUCURSAL_PROVINCIA = PROVINCIA
		WHERE SUPER_LOCALIDAD IS NOT NULL
		UNION
		SELECT DISTINCT PROVINCIA_ID, CLIENTE_LOCALIDAD
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].[PROVINCIA] ON CLIENTE_PROVINCIA = PROVINCIA
		WHERE CLIENTE_LOCALIDAD IS NOT NULL

	-- DIRECCION

	INSERT INTO [QUICK_SORT].[DIRECCION] (LOCALIDAD_ID, DIRECCION)
		SELECT DISTINCT LOCALIDAD_ID, SUPER_DOMICILIO
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].[LOCALIDAD] ON SUPER_LOCALIDAD = LOCALIDAD
		WHERE SUPER_DOMICILIO IS NOT NULL
		UNION
		SELECT DISTINCT LOCALIDAD_ID, SUCURSAL_DIRECCION
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].[LOCALIDAD] ON SUCURSAL_LOCALIDAD = LOCALIDAD
		WHERE SUCURSAL_DIRECCION IS NOT NULL
		UNION
		SELECT DISTINCT LOCALIDAD_ID, CLIENTE_DOMICILIO
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].[LOCALIDAD] ON CLIENTE_LOCALIDAD = LOCALIDAD
		WHERE CLIENTE_DOMICILIO IS NOT NULL

	-- MEDIO_PAGO_TIPO

    INSERT INTO [QUICK_SORT].[MEDIO_PAGO_TIPO] (MEDIO_PAGO_TIPO)
        SELECT DISTINCT PAGO_TIPO_MEDIO_PAGO
        FROM [gd_esquema].[Maestra] 
        WHERE PAGO_TIPO_MEDIO_PAGO IS NOT NULL

    -- PAGO_MEDIO_PAGO

    INSERT INTO [QUICK_SORT].[PAGO_MEDIO_PAGO] (MEDIO_PAGO_TIPO_ID,PAGO_MEDIO_PAGO)
        SELECT DISTINCT t.MEDIO_PAGO_TIPO_ID,PAGO_MEDIO_PAGO
        FROM [gd_esquema].[Maestra] m
        JOIN [QUICK_SORT].[MEDIO_PAGO_TIPO] t ON m.PAGO_TIPO_MEDIO_PAGO=t.MEDIO_PAGO_TIPO
        WHERE PAGO_MEDIO_PAGO IS NOT NULL

	-- DESCUENTO MEDIO PAGO

	INSERT INTO [QUICK_SORT].[DESCUENTO_MEDIO_PAGO](DESCUENTO_MEDIO_PAGO_CODIGO, DESCUENTO_PAGO_MEDIO_PAGO_ID , DESCUENTO_FECHA_INICIO,
	DESCUENTO_FECHA_FIN, DESCUENTO_PORCENTAJE, DESCUENTO_TOPE, DESCUENTO_DESCRIPCION)
		SELECT DISTINCT m.DESCUENTO_CODIGO, p.PAGO_MEDIO_PAGO_ID, m.DESCUENTO_FECHA_INICIO, m.DESCUENTO_FECHA_FIN, 
		m.DESCUENTO_PORCENTAJE_DESC, m.DESCUENTO_TOPE, m.DESCUENTO_DESCRIPCION
		FROM [gd_esquema].[Maestra] m
		JOIN [QUICK_SORT].[PAGO_MEDIO_PAGO] p ON p.PAGO_MEDIO_PAGO = m.PAGO_MEDIO_PAGO
		WHERE m.DESCUENTO_CODIGO IS NOT NULL AND m.PAGO_MEDIO_PAGO IS NOT NULL

	-- SUPERMERCADO

	INSERT INTO [QUICK_SORT].[SUPERMERCADO] (SUPER_CUIT, SUPER_DIRECCION_ID, SUPER_NOMBRE,
	SUPER_RAZON_SOC, SUPER_IIBB, SUPER_FECHA_INI_ACTIVIDAD, SUPER_CONDICION_FISCAL)
		SELECT DISTINCT SUPER_CUIT, DIRECCION_ID, SUPER_NOMBRE, SUPER_RAZON_SOC, SUPER_IIBB, SUPER_FECHA_INI_ACTIVIDAD,
		SUPER_CONDICION_FISCAL
		FROM [gd_esquema].[Maestra]
		JOIN [QUICK_SORT].[DIRECCION] ON SUPER_DOMICILIO = DIRECCION
		WHERE SUPER_CUIT IS NOT NULL 

	-- SUCURSAL
	
	INSERT INTO [QUICK_SORT].[SUCURSAL] (SUCURSAL_SUPER_CUIT, SUCURSAL_DIRECCION_ID, SUCURSAL_NOMBRE)
		SELECT DISTINCT s.SUPER_CUIT, d.DIRECCION_ID, m.SUCURSAL_NOMBRE
		FROM [gd_esquema].[Maestra] m
		JOIN [QUICK_SORT].[DIRECCION] d ON m.SUCURSAL_DIRECCION = d.DIRECCION
		JOIN [QUICK_SORT].[SUPERMERCADO] s ON s.SUPER_CUIT = m.SUPER_CUIT
		WHERE SUCURSAL_NOMBRE IS NOT NULL

	-- EMPLEADO
	
	INSERT INTO [QUICK_SORT].[EMPLEADO] (EMPLEADO_SUCURSAL_ID, EMPLEADO_NOMBRE, EMPLEADO_APELLIDO, 
	EMPLEADO_FECHA_REGISTRO, EMPLEADO_TELEFONO, EMPLEADO_MAIL, EMPLEADO_FECHA_NACIMIENTO, EMPLEADO_DNI)
		SELECT DISTINCT s.SUCURSAL_ID, m.EMPLEADO_NOMBRE, m.EMPLEADO_APELLIDO, m.EMPLEADO_FECHA_REGISTRO, m.EMPLEADO_TELEFONO,
		m.EMPLEADO_MAIL, m.EMPLEADO_FECHA_NACIMIENTO, m.EMPLEADO_DNI
		FROM [gd_esquema].[Maestra] m
		JOIN [QUICK_SORT].[SUCURSAL] s ON s.SUCURSAL_NOMBRE = m.SUCURSAL_NOMBRE
		WHERE EMPLEADO_DNI IS NOT NULL

	--CLIENTE

	INSERT INTO [QUICK_SORT].[CLIENTE] (CLIENTE_DIRECCION_ID,CLIENTE_DNI,CLIENTE_NOMBRE,CLIENTE_APELLIDO,
		CLIENTE_FECHA_REGISTRO,CLIENTE_TELEFONO,CLIENTE_MAIL,CLIENTE_FECHA_NACIMIENTO)
		SELECT DISTINCT DIRECCION_ID,CLIENTE_DNI,CLIENTE_NOMBRE,CLIENTE_APELLIDO,
		CLIENTE_FECHA_REGISTRO,CLIENTE_TELEFONO,CLIENTE_MAIL,CLIENTE_FECHA_NACIMIENTO
		FROM [gd_esquema].[Maestra]
        JOIN [QUICK_SORT].[DIRECCION] ON CLIENTE_DOMICILIO = DIRECCION
		WHERE CLIENTE_DNI IS NOT NULL

	-- TICKET_TIPO_COMPROBANTE
	
	INSERT INTO [QUICK_SORT].[TICKET_TIPO_COMPROBANTE] (TICKET_TIPO_COMPROBANTE)
		SELECT DISTINCT TICKET_TIPO_COMPROBANTE
		FROM [gd_esquema].[Maestra]

	-- CAJA_TIPO

	INSERT INTO [QUICK_SORT].[CAJA_TIPO] (CAJA_TIPO)
		SELECT DISTINCT CAJA_TIPO
		FROM [gd_esquema].[Maestra]
		WHERE CAJA_TIPO IS NOT NULL	
	
	-- ESTADO

	INSERT INTO [QUICK_SORT].[ESTADO] (ESTADO_TIPO)
		SELECT DISTINCT ENVIO_ESTADO
		FROM [gd_esquema].[Maestra]
		WHERE ENVIO_ESTADO IS NOT NULL
	
	-- CAJA

	INSERT INTO [QUICK_SORT].[CAJA] (CAJA_SUCURSAL_ID, CAJA_TIPO_ID, CAJA_NUMERO)
		SELECT DISTINCT s.SUCURSAL_ID, c.CAJA_TIPO_ID, m.CAJA_NUMERO 
		FROM [QUICK_SORT].[SUCURSAL] s 
		JOIN [gd_esquema].[Maestra] m on s.sucursal_nombre = m.SUCURSAL_NOMBRE
		JOIN [QUICK_SORT].[CAJA_TIPO] c on c.CAJA_TIPO = m.CAJA_TIPO

	-- TICKET TODO: TICKET_TOTAL_PROMOCIONES: no es el ticket_total_descuento_aplicado?
	INSERT INTO [QUICK_SORT].[TICKET](TICKET_SUCURSAL_ID, TICKET_EMPLEADO_LEGAJO, TICKET_CAJA_ID, TICKET_TIPO_COMPROBANTE_ID,
			TICKET_NRO, TICKET_TOTAL, TICKET_FECHA_HORA, TICKET_SUBTOTAL_PRODUCTOS, TICKET_DESCUENTO_MEDIO,
			TICKET_TOTAL_PROMOCIONES, TICKET_TOTAL_ENVIO)
		SELECT DISTINCT s.SUCURSAL_ID, e.EMPLEADO_LEGAJO, c.CAJA_SUCURSAL_ID, t.TICKET_TIPO_COMPROBANTE_ID, m.TICKET_NUMERO,
		m.TICKET_TOTAL_TICKET, m.TICKET_FECHA_HORA, m.TICKET_SUBTOTAL_PRODUCTOS, m.TICKET_TOTAL_DESCUENTO_APLICADO_MP,
		m.TICKET_TOTAL_DESCUENTO_APLICADO ,m.TICKET_TOTAL_ENVIO
		FROM gd_esquema.Maestra m 
		join [QUICK_SORT].[SUCURSAL] s on s.SUCURSAL_NOMBRE = m.SUCURSAL_NOMBRE 
		join [QUICK_SORT].[EMPLEADO] e on e.EMPLEADO_DNI = m.EMPLEADO_DNI
		join [QUICK_SORT].[CAJA] c on c.CAJA_SUCURSAL_ID = s.SUCURSAL_ID and c.CAJA_NUMERO = m.CAJA_NUMERO
		JOIN [QUICK_SORT].[TICKET_TIPO_COMPROBANTE] t ON t.TICKET_TIPO_COMPROBANTE = m.TICKET_TIPO_COMPROBANTE
		WHERE m.TICKET_TIPO_COMPROBANTE IS NOT NULL

	-- ENVIO

    INSERT INTO [QUICK_SORT].[ENVIO] (ENVIO_TICKET_ID,ENVIO_CLIENTE_ID,ENVIO_FECHA_PROGRAMADA,ENVIO_HORA_INICIO,
        ENVIO_HORA_FIN,ENVIO_FECHA_ENTREGA,ENVIO_COSTO)
        SELECT DISTINCT t.TICKET_ID,c.CLIENTE_ID,m.ENVIO_FECHA_PROGRAMADA,m.ENVIO_HORA_INICIO,
        m.ENVIO_HORA_FIN,m.ENVIO_FECHA_ENTREGA,m.ENVIO_COSTO
        FROM [gd_esquema].[Maestra] m
        JOIN [QUICK_SORT].[TICKET] t ON m.TICKET_NUMERO = t.TICKET_NRO AND m.TICKET_FECHA_HORA=t.TICKET_FECHA_HORA 
		AND m.TICKET_SUBTOTAL_PRODUCTOS=t.TICKET_SUBTOTAL_PRODUCTOS
        JOIN [QUICK_SORT].[CLIENTE] c ON m.CLIENTE_DNI=c.CLIENTE_DNI	
        WHERE ENVIO_FECHA_PROGRAMADA IS NOT NULL

	-- ESTADO_POR_ENVIO

	INSERT INTO [QUICK_SORT].[ESTADO_POR_ENVIO](ESTADO_ID, ENVIO_ID)
		SELECT DISTINCT es.ESTADO_ID, en.ENVIO_ID
		FROM [gd_esquema].[Maestra] m
		JOIN [QUICK_SORT].[ESTADO] es ON es.ESTADO_TIPO = m.ENVIO_ESTADO
		JOIN [QUICK_SORT].[ENVIO] en ON en.ENVIO_HORA_INICIO = m.ENVIO_HORA_INICIO AND en.ENVIO_FECHA_PROGRAMADA = m.ENVIO_FECHA_PROGRAMADA
		AND en.ENVIO_COSTO = m.ENVIO_COSTO

	-- DETALLE_TICKET

	INSERT INTO [QUICK_SORT].[DETALLE_TICKET](DETALLE_TICKET_TICKET_ID, PRODUCTO_ID, DETALLE_CANTIDAD,
				DETALLE_PRECIO_UNITARIO,DETALLE_TOTAL_PRODUCTO)
		SELECT DISTINCT t1.ticket_id, p.PRODUCTO_ID, m.TICKET_DET_CANTIDAD, m.TICKET_DET_PRECIO, m.TICKET_DET_TOTAL
		from [gd_esquema].[Maestra] m
		join [QUICK_SORT].[TICKET] t1 on t1.TICKET_NRO = m.TICKET_NUMERO and t1.TICKET_TOTAL = m.TICKET_TOTAL_TICKET AND
		t1.TICKET_SUBTOTAL_PRODUCTOS = m.TICKET_SUBTOTAL_PRODUCTOS and t1.TICKET_FECHA_HORA = m.TICKET_FECHA_HORA
		join [QUICK_SORT].[PRODUCTO] p ON p.PRODUCTO_NOMBRE = m.PRODUCTO_NOMBRE AND p.PRODUCTO_MARCA = m.PRODUCTO_MARCA and m.PRODUCTO_PRECIO = p.PRODUCTO_PRECIO
		WHERE m.PRODUCTO_NOMBRE IS NOT NULL AND m.PRODUCTO_MARCA IS NOT NULL
		AND p.PRODUCTO_ID IS NOT NULL

	-- PROMOCION

	INSERT INTO [QUICK_SORT].[PROMOCION] (PROMO_CODIGO,PROMO_DESCRIPCION, PROMO_FECHA_INICIO, PROMO_FECHA_FIN)
		SELECT DISTINCT PROMO_CODIGO,PROMOCION_DESCRIPCION,PROMOCION_FECHA_FIN,
		PROMOCION_FECHA_INICIO
		FROM [gd_esquema].[Maestra]
		WHERE PROMO_CODIGO IS NOT NULL

	-- REGLA_PROMOCION_PRODUCTO: TODO: ¿LINKEAR POR PRODUCTO Y TICKET?-> creo q ya esta

	INSERT INTO [QUICK_SORT].[REGLA_PROMOCION_PRODUCTO] (PROMO_CODIGO,PRODUCTO_ID)
		SELECT DISTINCT p.PROMO_CODIGO, pr.PRODUCTO_ID
		FROM [gd_esquema].[Maestra] m
		JOIN [QUICK_SORT].[PROMOCION] p ON p.PROMO_CODIGO = m.PROMO_CODIGO
		JOIN [QUICK_SORT].[PRODUCTO] pr ON pr.PRODUCTO_NOMBRE = m.PRODUCTO_NOMBRE 
		AND pr.PRODUCTO_DESCRIPCION = m.PRODUCTO_DESCRIPCION 
		AND pr.PRODUCTO_MARCA = m.PRODUCTO_MARCA
		WHERE m.PROMO_CODIGO IS NOT NULL 
	
	-- REGLA_PROMOCION

	INSERT INTO [QUICK_SORT].[REGLA_PROMOCION] (REGLA_PROMO_CODIGO,REGLA_DESCRIPCION,
			REGLA_DESCUENTO_APLICABLE,REGLA_CANTIDAD_APLICABLE,REGLA_CANTIDAD_APLICABLE_DESCUENTO,REGLA_CANTIDAD_MAXIMA,
			REGLA_APLICA_MISMA_MARCA,REGLA_APLICA_MISMO_PRODUCTO)
		SELECT DISTINCT p.PROMO_CODIGO,m.REGLA_DESCRIPCION,m.REGLA_DESCUENTO_APLICABLE_PROD,m.REGLA_CANT_APLICABLE_REGLA,m.REGLA_CANT_APLICA_DESCUENTO,m.REGLA_CANT_MAX_PROD,m.REGLA_APLICA_MISMA_MARCA,m.REGLA_APLICA_MISMO_PROD
		FROM [gd_esquema].[Maestra] m JOIN [QUICK_SORT].[PROMOCION] p ON p.PROMO_CODIGO = m.PROMO_CODIGO
		WHERE m.PROMO_CODIGO IS NOT NULL
		AND REGLA_DESCRIPCION IS NOT NULL
		AND REGLA_DESCUENTO_APLICABLE_PROD IS NOT NULL
		AND REGLA_CANT_APLICABLE_REGLA IS NOT NULL
		AND REGLA_CANT_APLICA_DESCUENTO IS NOT NULL
		AND REGLA_CANT_MAX_PROD IS NOT NULL
		AND REGLA_APLICA_MISMA_MARCA IS NOT NULL
		AND REGLA_APLICA_MISMO_PROD IS NOT NULL

	-- DETALLE_POR_PROMOCION TODO: PROMO_TOTAL

	INSERT INTO [QUICK_SORT].[DETALLE_POR_PROMOCION] (DETALLE_TICKET_ID,PROMO_CODIGO,PROMO_TOTAL)
		SELECT DISTINCT d.DETALLE_TICKET_ID, p.PROMO_CODIGO, m.PROMO_APLICADA_DESCUENTO
		FROM [gd_esquema].[Maestra] m
		 JOIN [QUICK_SORT].[PROMOCION] p ON p.PROMO_CODIGO = m.PROMO_CODIGO
		 JOIN [QUICK_SORT].[PRODUCTO] pr ON pr.PRODUCTO_NOMBRE = m.PRODUCTO_NOMBRE AND 
		 pr.PRODUCTO_DESCRIPCION = m.PRODUCTO_DESCRIPCION AND pr.PRODUCTO_PRECIO = m.PRODUCTO_PRECIO AND
		 pr.PRODUCTO_MARCA = m.PRODUCTO_MARCA
		JOIN [QUICK_SORT].[TICKET] t ON t.TICKET_NRO = m.TICKET_NUMERO and t.TICKET_FECHA_HORA = m.TICKET_FECHA_HORA 
			and t.TICKET_SUBTOTAL_PRODUCTOS = m.TICKET_SUBTOTAL_PRODUCTOS
		JOIN [QUICK_SORT].[DETALLE_TICKET] d ON d.DETALLE_TICKET_TICKET_ID = t.TICKET_ID and d.PRODUCTO_ID = pr.PRODUCTO_ID 
		and d.DETALLE_CANTIDAD = m.TICKET_DET_CANTIDAD

	-- DETALLE_PAGO

    INSERT INTO [QUICK_SORT].[DETALLE_PAGO] (DET_PAGO_CLIENTE_ID,DET_PAGO_NRO_TARJETA,DET_PAGO_FECHA_VEN_TARJETA,DET_PAGO_CUOTAS)
		SELECT DISTINCT e.ENVIO_CLIENTE_ID,m.PAGO_TARJETA_NRO,m.PAGO_TARJETA_FECHA_VENC,m.PAGO_TARJETA_CUOTAS
			FROM [gd_esquema].[Maestra] m 
			JOIN [QUICK_SORT].[TICKET] t ON t.TICKET_NRO = m.TICKET_NUMERO and t.TICKET_FECHA_HORA = m.TICKET_FECHA_HORA 
			and t.TICKET_SUBTOTAL_PRODUCTOS = m.TICKET_SUBTOTAL_PRODUCTOS
			JOIN [QUICK_SORT].[ENVIO] e ON e.ENVIO_TICKET_ID = t.TICKET_ID 
			WHERE PAGO_TARJETA_NRO IS NOT NULL
    
    -- PAGO

    INSERT INTO [QUICK_SORT].[PAGO] (PAGO_TICKET_ID,PAGO_MEDIO_PAGO_ID,DETALLE_PAGO_ID,PAGO_FECHA,PAGO_IMPORTE,PAGO_DESCUENTO_APLICADO)
        SELECT DISTINCT t.TICKET_ID,p.PAGO_MEDIO_PAGO_ID,d.DETALLE_PAGO_ID,PAGO_FECHA,PAGO_IMPORTE,PAGO_DESCUENTO_APLICADO 
        FROM [gd_esquema].[Maestra] m 
        JOIN [QUICK_SORT].[PAGO_MEDIO_PAGO] p ON m.PAGO_MEDIO_PAGO=p.PAGO_MEDIO_PAGO
        JOIN [QUICK_SORT].[TICKET] t ON m.TICKET_NUMERO = t.TICKET_NRO AND m.TICKET_FECHA_HORA=t.TICKET_FECHA_HORA AND m.TICKET_SUBTOTAL_PRODUCTOS=t.TICKET_SUBTOTAL_PRODUCTOS 
        JOIN [QUICK_SORT].[DETALLE_PAGO] d ON m.PAGO_TARJETA_CUOTAS=d.DET_PAGO_CUOTAS AND m.PAGO_TARJETA_FECHA_VENC=d.DET_PAGO_FECHA_VEN_TARJETA AND m.PAGO_TARJETA_NRO=d.DET_PAGO_NRO_TARJETA 
        JOIN [QUICK_SORT].[CLIENTE] c ON d.DET_PAGO_CLIENTE_ID=c.CLIENTE_ID AND m.CLIENTE_DNI=c.CLIENTE_DNI
        WHERE PAGO_FECHA IS NOT NULL

END
GO

EXEC [QUICK_SORT].[MIGRAR]

GO
